export const seedSkills = [
  {
    id: "academic-paper-composer",
    name: "academic-paper-composer",
    description: "根据真实项目材料生成和润色本科论文定稿。",
    installed: true,
    enabled: true,
    source: "local",
    status: "healthy",
    version: "1.4.2",
    updatedAt: "今天 01:16",
    path: "~/.codex/skills/academic-paper-composer",
    triggers: ["论文定稿", "降重", "排版"],
  },
  {
    id: "frontend-app-builder",
    name: "frontend-app-builder",
    description: "从概念图到可运行前端，包含视觉 QA 与响应式检查。",
    installed: true,
    enabled: false,
    source: "plugin",
    status: "update",
    version: "0.9.8",
    updatedAt: "昨天 22:40",
    path: "~/.codex/plugins/cache/openai-curated/build-web-apps",
    triggers: ["前端", "仪表盘", "网页"],
  },
  {
    id: "test-driven-development",
    name: "test-driven-development",
    description: "先写失败测试，再写最小实现，保护行为边界。",
    installed: true,
    enabled: true,
    source: "system",
    status: "healthy",
    version: "2.1.0",
    updatedAt: "本周一",
    path: "~/.codex/skills/test-driven-development",
    triggers: ["功能", "修复", "重构"],
  },
  {
    id: "skill-installer",
    name: "skill-installer",
    description: "从官方列表或 GitHub 仓库下载安装到本地 skills。",
    installed: true,
    enabled: true,
    source: "system",
    status: "healthy",
    version: "1.2.0",
    updatedAt: "本周二",
    path: "~/.codex/skills/.system/skill-installer",
    triggers: ["下载 skill", "安装 skill", "list skills"],
  },
  {
    id: "japanese-tutor",
    name: "japanese-tutor",
    description: "交互式日语学习助手，可做词汇、语法、测验和材料解析。",
    installed: false,
    enabled: false,
    source: "github",
    status: "available",
    version: "remote",
    updatedAt: "可安装",
    path: "openclaw/skills/skills/chndranndr/japanese-tutor",
    triggers: ["日语", "翻译", "语法"],
  },
  {
    id: "systematic-debugging",
    name: "systematic-debugging",
    description: "遇到异常行为时，按证据链定位、复现、假设和验证。",
    installed: true,
    enabled: true,
    source: "local",
    status: "healthy",
    version: "1.5.1",
    updatedAt: "6 月 15 日",
    path: "~/.codex/skills/systematic-debugging",
    triggers: ["bug", "测试失败", "异常"],
  },
  {
    id: "openai-docs",
    name: "openai-docs",
    description: "查询 OpenAI 官方 API 与产品文档，适合模型和 SDK 问题。",
    installed: false,
    enabled: false,
    source: "curated",
    status: "available",
    version: "remote",
    updatedAt: "官方精选",
    path: "openai/skills/skills/.curated/openai-docs",
    triggers: ["OpenAI API", "Responses", "Agents SDK"],
  },
];

export const initialActivity = [
  {
    id: "act-1",
    title: "刷新完成",
    detail: "扫描到 5 个本地 skill，2 个可安装候选。",
    tone: "good",
    time: "刚刚",
  },
  {
    id: "act-2",
    title: "发现更新",
    detail: "frontend-app-builder 有新版本可同步。",
    tone: "warn",
    time: "3 分钟前",
  },
  {
    id: "act-3",
    title: "索引正常",
    detail: "触发词、来源和状态索引已重建。",
    tone: "neutral",
    time: "8 分钟前",
  },
];
